-- Remove unused scaffolding tables.
--
-- Migrations 000004 through 000032 created a large speculative surface
-- (knowledge graph, economic intelligence, digital twins, federation, IoT,
-- deliberation rooms, agent registries and so on) that no Go code reads and
-- that the product scope places in later phases. Leaving them in place made the
-- schema 147 tables wide and misleading.
--
-- Everything dropped here is unreferenced by internal/, pkg/ and cmd/. Tables
-- that later phases will need (knowledge sources and chunks, conversation and
-- message history, skills, interests, organizer profiles, the campus and tenant
-- rows behind users.tenant_id) are deliberately kept.
--
-- This migration is one-way: recreating a hundred tables is not something a
-- rollback should attempt. The files that created them remain in git history.

DROP TABLE IF EXISTS
    action_executions,
    action_plans,
    agent_memory,
    agent_registry,
    agent_tools,
    ai_cost_metrics,
    ai_decision_metadata,
    ai_incidents,
    argument_graphs,
    automation_executions,
    automation_loop_guards,
    automation_rules,
    autonomy_policies,
    autonomous_policies,
    autonomous_tasks,
    campus_state_snapshots,
    career_paths,
    causal_relationships,
    collective_reasoning_jobs,
    curriculum_graph_edges,
    curriculum_graph_nodes,
    decision_outcomes,
    decision_records,
    decision_rooms,
    deliberation_rooms,
    digital_twin_state,
    digital_twins,
    dt_early_warnings,
    dt_interventions,
    dt_model_cards,
    dt_population_cohorts,
    dt_simulations,
    dt_system_snapshots,
    econ_datasets,
    econ_funding_opportunities,
    econ_indicators,
    econ_regional_balances,
    econ_scenarios,
    econ_tech_trends,
    ecosystem_contingency_plans,
    ecosystem_early_warnings,
    ecosystem_institutions,
    ecosystem_partnerships,
    ecosystem_strategic_plans,
    embeddings,
    enterprise_connectors,
    evidence_graphs,
    federated_knowledge_claims,
    federation_agreements,
    federation_disputes,
    federation_members,
    federation_trusts,
    global_agents,
    global_decision_arguments,
    global_decision_forecasts,
    global_decision_journals,
    global_decision_options,
    global_decision_rooms,
    global_forecasts,
    global_risks,
    global_strategic_plans,
    global_trust_entities,
    governance_proposals,
    governance_reviews,
    human_ai_teams,
    institutional_analytics,
    institutional_playbooks,
    intelligence_improvements,
    invention_disclosures,
    iot_commands,
    iot_devices,
    job_roles,
    kg_claims,
    kg_entities,
    kg_hypotheses,
    kg_relationships,
    kg_sources,
    knowledge_gaps,
    lessons_learned,
    lifelong_profiles,
    model_evaluations,
    operational_incidents,
    prediction_ledger,
    recommendation_feedback,
    replication_studies,
    research_artifacts,
    research_datasets,
    research_experiments,
    research_funding,
    research_hypotheses,
    research_projects,
    research_publications,
    research_workspaces,
    resource_reservations,
    scientific_claims,
    scientific_experiments,
    scientific_hypotheses,
    search_history,
    security_policies,
    service_catalog,
    simulation_runs,
    simulation_scenarios,
    talent_matches,
    task_approvals,
    tool_calls,
    tool_registry,
    trusted_institutions,
    twin_state_history,
    verified_experiences,
    workforce_skills,
    workspace_members;